apiVersion : apps/v1
kind: Deployment
metadata:
  name: "k8-b0c3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "k8-b0c3"
  template:
    metadata:
      labels:
        app: "k8-b0c3"
    spec:
      containers:
        - name: "k8-b0c3"
          image: "k8practice.azurecr.io/k8"
          ports:
          - containerPort: 80